### ISSUE TITLE
Error after running for the first time

### ISSUE THREAD

**Issue by rms2219** [aurimasniekis/idea-php-psr4-namespace-detector#1]
> Argument for @NotNull parameter 'file' of com/intellij/psi/impl/PsiManagerImpl.findFile must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/psi/impl/PsiManagerImpl.findFile must not be null
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java)
	at com.aurimasniekis.phppsr4namespacedetector.PhpPsr4NamespaceRootDetector.processNamespaces(PhpPsr4NamespaceRootDetector.java:119)
	at com.aurimasniekis.phppsr4namespacedetector.PhpPsr4NamespaceRootDetector.lambda$null$0(PhpPsr4NamespaceRootDetector.java:35)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.aurimasniekis.phppsr4namespacedetector.PhpPsr4NamespaceRootDetector.lambda$detectNamespaceRoots$1(PhpPsr4NamespaceRootDetector.java:34)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:267)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

When I used this plugin for the first time, I received this error. There were no new namespaces found. Also, I had just restarted PHPStorm after updating to 2017.1.2

EDIT: I can confirm that I receive this IDE fatal error every time I run the plugin.

**Comment by aurimasniekis** [comment]
Ahh, i see i did not tested if composer.json file is not present...

**Comment by aurimasniekis** [comment]
Until JetBrains approves plugin u can use jar file from Releases and install as File Plugin
